### ISSUE TITLE
Figure out a cleaner way to manage .solr_wrapper

### ISSUE THREAD

**Issue by mark-dce** [samvera/hydra#114]
E.G. in the dive-into-hydra tutorial at https://github.com/projecthydra/hydra/wiki/Lesson---Start-FCRepo-and-Solr#step-1-start-solr 

Solr seems to withdraw older versions sooner than we'd like, might need to find a different archive location, remove the version from the wrapper file, or ....

**Comment by cbeer** [comment]
We addressed that in solr_wrapper a couple releases ago; it'll go to the apache archive for non-current releases.
