### ISSUE TITLE
Connection to W3C CG Hydra?

### ISSUE THREAD

**Issue by berezovskyi** [samvera/hydra#146]
Hi, is this project connected to http://www.hydra-cg.com/ https://www.w3.org/community/hydra/ in any way? You are both in the linked data space and it seems confusing to me.

cc @lanthaler as the W3C Hydra CG chair.

**Comment by berezovskyi** [comment]
Or does a true Hydra need to have many heads? 😉

**Comment by cjcolvar** [comment]
No this project is not related to the W3C Hydra CG.

Hydra was the former name of [Samvera](https://samvera.org), a framework for making digital asset management repositories for libraries, archives, and museums.  Applications built using Samvera components usually use [Fedora Commons](http://fedorarepository.org/), a [Linked Data Platform](https://en.wikipedia.org/wiki/Linked_Data_Platform) server.  The old name of Hydra is still present in some repository names and code like this repository.

**Comment by berezovskyi** [comment]
Yes, thank you!

–Andrew.
(sent from my phone)
