### ISSUE TITLE
Move grant_revoke_gem_authority.rb to samvera-labs/maintenance

### ISSUE THREAD

**Issue by tpendragon** [samvera/hydra#151]

**Comment by jcoyne** [comment]
Why?

**Comment by rotated8** [comment]
https://github.com/samvera/hydra/issues/150, I think.

**Comment by jcoyne** [comment]
I'm +1 to #150, but I don't understand why hydra-head would be a good place for that.  It's completely unrelated to the functionality of hydra-head. I'd say give it its own place. `samvera-scripts` or something?

**Comment by cjcolvar** [comment]
I'm with @jcoyne in that I don't think it really fits in `hydra-head`.

**Comment by tpendragon** [comment]
Ah, yes, I should do that - it just didn't auto-close this so I lost track.
